coverage:
  range: 80..100
  round: down
  precision: 2
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 5%

# Test files aren't important for coverage
ignore:
  - "tests"

# Make comments less noisy
comment:
  layout: "files"
  require_changes: yes
